### ISSUE TITLE
Ubuntu 20.4 run build_katran.sh ERROR : too many initializers for ‘perf_buffer_opts’

### ISSUE THREAD

**Issue by shaoxiqian** [facebookincubator/katran#146]
[ 50%] Building CXX object katran/lib/CMakeFiles/katranlb.dir/MonitoringServiceCore.cpp.o
/root/katran/katran/lib/PerfBufferEventReader.cpp: In member function ‘bool katran::PerfBufferEventReader::open(int, folly::EventBase*, size_t)’:
/root/katran/katran/lib/PerfBufferEventReader.cpp:66:3: error: too many initializers for ‘perf_buffer_opts’
   66 |   };
      |   ^
make[2]: *** [katran/lib/CMakeFiles/katranlb.dir/build.make:141: katran/lib/CMakeFiles/katranlb.dir/PerfBufferEventReader.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:402: katran/lib/CMakeFiles/katranlb.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by bienkma** [comment]
Checkout to this commit and build again. I worked with hash commit in Ubuntu 18.04(64bits)
```sh
git clone https://github.com/facebookincubator/katran.git
cd katran
git checkout -b "build" 4cdc88bfb3b9f9a989273583b649838ac4eb94d6
./build_katran.sh
```

**Comment by udippant** [comment]
Can you try now after https://github.com/facebookincubator/katran/commit/8e68514bf6b12e1f1dac94e706b189408ea9c553 ?

**Comment by shaoxiqian** [comment]
it seems fixed after upgrading the version of gcc. But the another problem ....
[100%] Built target katran_server_grpc
+ popd
~/katran/_build
+ /home/ubuntu/katran/build_bpf_modules_opensource.sh -s /home/ubuntu/katran -b /home/ubuntu/katran/_build
/home/ubuntu/katran/_build/deps/clang/clang+llvm-12.0.0-x86_64-linux-gnu-ubuntu-20.04/bin/clang -I./usr/include -I./include   \
-DDEBUG -D__KERNEL__ -Wno-unused-value -Wno-pointer-sign \
        -Wno-compare-distinct-pointer-types \
        -O2 -emit-llvm -c -g bpf/balancer_kern.c -o -| /home/ubuntu/katran/_build/deps/clang/clang+llvm-12.0.0-x86_64-linux-gnu-ubuntu-20.04/bin/llc -march=bpf -filetype=obj -o bpf/balancer_kern.o
Makefile:39: recipe for target 'bpf/balancer_kern.o' failed

**Comment by udippant** [comment]
Can you share more details on build failures? Can you share a paste (e.g. via gist) with the build logs?

**Comment by aminvakil** [comment]
I have tested using latest commit (which currently is https://github.com/facebookincubator/katran/commit/cf6aa04a0e0b60a5ba5ad7c72be7a3a537769d40) and commit (https://github.com/facebookincubator/katran/commit/8e68514bf6b12e1f1dac94e706b189408ea9c553), both fails with this:
```
$ bash build_bpf_modules_opensource.sh 
+ getopts :hb:s:d:m arg
+ shift 0
+ '[' -z '' ']'
++ pwd
+ echo -e '[ INFO ] BUILD_DIR is not set. So setting it as default to /home/aminvakil/katran'
[ INFO ] BUILD_DIR is not set. So setting it as default to /home/aminvakil/katran
++ pwd
+ BUILD_DIR=/home/aminvakil/katran/_build/
+ '[' -z '' ']'
++ pwd
+ echo -e '[ INFO ] SRC_DIR is not set. So setting it as default to /home/aminvakil/katran '
[ INFO ] SRC_DIR is not set. So setting it as default to /home/aminvakil/katran 
++ pwd
+ SRC_DIR=/home/aminvakil/katran
+ CLANG_PATH=/home/aminvakil/katran/_build//deps/clang/clang+llvm-12.0.0-x86_64-linux-gnu-ubuntu-20.04
+ '[' -f /etc/redhat-release ']'
+ rm -rf /home/aminvakil/katran/_build//deps/bpfprog
+ mkdir -p /home/aminvakil/katran/_build//deps/bpfprog/include
+ cp /home/aminvakil/katran/katran/lib/Makefile-bpf /home/aminvakil/katran/_build//deps/bpfprog/Makefile
+ cp -r /home/aminvakil/katran/katran/lib/bpf /home/aminvakil/katran/_build//deps/bpfprog/
+ cp -r /home/aminvakil/katran/katran/decap/bpf /home/aminvakil/katran/_build//deps/bpfprog/
+ cp /home/aminvakil/katran/katran/lib/linux_includes/bpf.h /home/aminvakil/katran/katran/lib/linux_includes/bpf_common.h /home/aminvakil/katran/katran/lib/linux_includes/bpf_endian.h /home/aminvakil/katran/katran/lib/linux_includes/bpf_helpers.h /home/aminvakil/katran/katran/lib/linux_includes/jhash.h /home/aminvakil/katran/_build//deps/bpfprog/include/
+ cd /home/aminvakil/katran/_build//deps/bpfprog
+ LD_LIBRARY_PATH=/home/aminvakil/katran/_build//deps/clang/clang+llvm-12.0.0-x86_64-linux-gnu-ubuntu-20.04/lib
+ make EXTRA_CFLAGS= LLC=/home/aminvakil/katran/_build//deps/clang/clang+llvm-12.0.0-x86_64-linux-gnu-ubuntu-20.04/bin/llc CLANG=/home/aminvakil/katran/_build//deps/clang/clang+llvm-12.0.0-x86_64-linux-gnu-ubuntu-20.04/bin/clang
/home/aminvakil/katran/_build//deps/clang/clang+llvm-12.0.0-x86_64-linux-gnu-ubuntu-20.04/bin/clang -I./usr/include -I./include   \
-DDEBUG -D__KERNEL__ -Wno-unused-value -Wno-pointer-sign \
        -Wno-compare-distinct-pointer-types \
        -O2 -emit-llvm -c -g bpf/balancer_kern.c -o -| /home/aminvakil/katran/_build//deps/clang/clang+llvm-12.0.0-x86_64-linux-gnu-ubuntu-20.04/bin/llc -march=bpf -filetype=obj -o bpf/balancer_kern.o
/home/aminvakil/katran/_build//deps/clang/clang+llvm-12.0.0-x86_64-linux-gnu-ubuntu-20.04/bin/clang/home/aminvakil/katran/_build//deps/clang/clang+llvm-12.0.0-x86_64-linux-gnu-ubuntu-20.04/bin/llc: error while loading shared libraries: : libtinfo.so.6error while loading shared libraries: : cannot open shared object filelibtinfo.so.6: : No such file or directorycannot open shared object file
: No such file or directory
Makefile:39: recipe for target 'bpf/balancer_kern.o' failed
make: *** [bpf/balancer_kern.o] Error 127
```

**Comment by aminvakil** [comment]
Also full log of executing `bash build_katran.sh`:

https://gist.github.com/aminvakil/219264247c64bc5eef04510a8f5b8891

Keep note that due to poor downloading from github releases from server I've disabled downloading clang from script and have put it manually in right place.

```
$ git diff
diff --git a/build_katran.sh b/build_katran.sh
index 61563fbb..cc49ea9e 100755
--- a/build_katran.sh
+++ b/build_katran.sh
@@ -277,13 +277,13 @@ get_clang() {
         sudo yum install -y clang llvm
     else
         CLANG_DIR=$DEPS_DIR/clang
-        rm -rf "$CLANG_DIR"
+        # rm -rf "$CLANG_DIR"
         pushd .
         mkdir -p "$CLANG_DIR"
         cd "$CLANG_DIR"
         echo -e "${COLOR_GREEN}[ INFO ] Downloading Clang ${COLOR_OFF}"
         # download platform appropriate version (9.0+) of clang from https://github.com/llvm/llvm-project/releases/
-        wget https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.0/clang+llvm-12.0.0-x86_64-linux-gnu-ubuntu-20.04.tar.xz
+        # wget https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.0/clang+llvm-12.0.0-x86_64-linux-gnu-ubuntu-20.04.tar.xz
         tar xvf ./clang+llvm-12.0.0-x86_64-linux-gnu-ubuntu-20.04.tar.xz
         echo -e "${COLOR_GREEN}Clang is installed ${COLOR_OFF}"
         popd
```

**Comment by avasylev** [comment]
@aminvakil I just compiled on vanilla Ubuntu 20.04 with no errors. If you still have the problem, please re-open.
